export * from './servicos';
export * from './sobre';
export * from './video';
export * from './mapa';
export * from './galeria';
export * from './formulario';
export * from './blog';
export * from './faq';
export * from './depoimentos';
